#!/bin/sh
# prerm script for apptemplate
#
# see: dh_installdeb(1)

set -e

. /usr/share/debconf/confmodule

if [ -f /usr/share/dbconfig-common/dpkg/prerm ]; then
    . /usr/share/dbconfig-common/dpkg/prerm
    dbc_go apptemplate "$@"
fi

case "$1" in
    remove|upgrade|deconfigure|purge)
    rm -rf /usr/lib/apptemplate/composer.lock /var/lib/apptemplate /usr/lib/apptemplate/.env
    ;;

    failed-upgrade)
    ;;

    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0


